export const FETCH_SEARCH_MAIN_INFO_REQUEST = "FETCH_SEARCH_MAIN_INFO_REQUEST";
export const FETCH_SEARCH_MAIN_INFO_SUCCESS = "FETCH_SEARCH_MAIN_INFO_SUCCESS";
export const FETCH_SEARCH_MAIN_INFO_FAILURE = "FETCH_SEARCH_MAIN_INFO_FAILURE";
export const SELECT_SEARCH_ITEM = "SELECT_SEARCH_ITEM";
